services:
  configuration-processor:
    build: .
    container_name: theconfiguration-processor
    ports:
      - "5050:5050"
    volumes:
      - ./samples:/app/samples:ro
      - ./output:/app/output
      - ./.env:/app/.env:ro
    restart: unless-stopped
